### ISSUE TITLE
RGB led container not working on dev 1.1 board?

### ISSUE THREAD

**Issue by nicojanssens** [balena-io/balena-fin-examples#5]
Hi,

I deployed all example containers on a new fin dev 1.1 board. 

The wifi-connect container works fine -- I was able to connect to the balenaFin hotspot and configured the wifi settings using the built-in web-service.

The rgb-led container gets activate, and it generates output messages about led status changes. The led on the board itself, however, doesn't light up. Was this working before on other dev 1.1 boards?

Thanks,
Nico.

**Comment by floion** [comment]
@curcuz are there known issues about this?

**Comment by azaiter** [comment]
This [PR](https://github.com/balena-io/balena-fin-examples/pull/6) solves it, just make sure to follow remove the backslash after pca963x in the IC color brightness paths in order to have it working.

**Comment by chrisys** [comment]
I've just updated the above PR that @azaiter mentions, but until it gets merged you can deploy the `update-led-example` branch to see it working on the 1.1 board. I have it deployed to a fleet of mixed v1.0 and v1.1 boards and it works across them all.

**Comment by chrisys** [comment]
OK https://github.com/balena-io/balena-fin-examples/pull/6 is now merged which fixes this - thanks for creating the issue!
